<div class="content" style="position: absolute; top: 10px; right: 10px">
    <select id="mySelector" style="margin: 20px">
        <option value="2">Два</option>
        <option value="3">Три</option>
        <option value="4">Четыре</option>
    </select>
</div>
<div id="second" class="container content">
  <div id="left">
    <ol class="container">
      <li class="active" value="0">Задание</li>
      <li value="1">Задание</li>
      <li value="2">Задание</li>
      <li value="3">Задание</li>
      <li value="4">Задание</li>
    </ol>
  </div>
  <div id="middle">
    <div id="exercice"></div>
    <div id="solution"></div>
  </div>
  <div id="right">
  </div>
</div>
<div id="third" class="container content" style="display: none; height: 20px;">
    <a href="/application/ne/hochu/zamorachivatsya/3/1/index.php" target="_blank"><div>Щелк 1</div></a>
    <a href="/application/ne/hochu/zamorachivatsya/3/2/index.php" target="_blank"><div>Щелк 2</div></a>
    <a href="/application/ne/hochu/zamorachivatsya/3/3/index.php" target="_blank"><div>Щелк 3</div></a>
    <a href="/application/ne/hochu/zamorachivatsya/3/4/index.php" target="_blank"><div>Щелк 4</div></a>
</div>
<div id="fourth" class="container content" style="display: none; height: 20px;">
    <a href="/application/ne/hochu/zamorachivatsya/4/index.php" target="_blank"><div>ЩЕЛКККК</div></a>
</div>

<script src="application/assets/js/lab2.js" type="text/javascript"></script>