<div id="second" class="container content" style="display: none">
  <div id="left">
    <ol class="container">
      <li class="active" value="0">Задание</li>
      <li value="1">Задание</li>
      <li value="2">Задание</li>
      <li value="3">Задание</li>
      <li value="4">Задание</li>
    </ol>
  </div>
  <div id="middle">
    <div id="exercice"></div>
    <div id="solution"></div>
  </div>
  <div id="right">
  </div>
</div>
<div id="third" class="container content" >
    <button onclick="pressButton()" value="Press to see"></button>
</div>

<script src="application/assets/js/lab2.js" type="text/javascript"></script>
<script>
    function pressButton() {
        // Display an external page using an iframe
        var src = "application/ne/hochu/zamorachivatsya/3/1/index.php";
        $.modal('<iframe src="' + src + '" style="border:0;width:100%;height:100%;">');
        return false;
    }
</script>