<div id="content" class="container">
  <div id="left">
    <ol class="container">
      <li class="active" value="0">Задание</li>
      <li value="1">Задание</li>
      <li value="2">Задание</li>
      <li value="3">Задание</li>
      <li value="4">Задание</li>
    </ol>
  </div>
  <div id="middle">
    <div id="exercice"></div>
    <div id="solution">
        <label>Выберите номер месяца</label>
        <form action="/application/sols/first.php" target="_blank">
            <input type="number" min="1" max="12" name="month" value="<? echo $currMonth?>"/>
            <p>Месяц: <script>getMonth()</script></p>
          <button type="submit">Send</button>
        </form>
    </div>
  </div>
  <div id="right">
  </div>
</div>

<script type="text/javascript">
  var ex = [
      '<div>Составить программу, которая по порядковому номеру месяца определяет время года, к которому относится этот месяц.</div>',
      '<div>Имеется n бактерий красного цвета. Через 1 такт времени красная бактерия меняется на зелёную, затем через 1 такт ' +
      'времени делится на красную и зелёную. Сколько будет всех бактерий через k тактов времени?</div>',
      '<div>Заполнить двумерный массив размерностью NxN(N нечётное число) ' +
      'целыми числами от1 до N*N по следующим правилам:<br>' +
      'a) единица помещается в среднюю клетку первой строки;<br>' +
      'b) заполнение массива происходит по диагоналям вправо и вверх;<br>' +
      'c) при достижении верхней строки следующее число помещается в нижнюю ' +
      'строку так, как будто она находится над верхней строкой; ' +
      '2<br>' +
      'd) при достижении крайнего правого столбца следующее число помещается ' +
      'в крайний левый столбец так, как будто он находится около крайнего ' +
      'правого столбца;<br>' +
      'e) при достижении верхней клетки крайнего правого столбца следует опуститься ' +
      'на одну строку ниже в вертикальном порядке и продолжать заполнение ' +
      'клеток по правилу;<br>' +
      'f) если клетка уже заполнена, следует опуститься на одну строку ниже в ' +
      'вертикальном порядке и продолжать заполнение клеток по правилу</div>',
      '<div>Задана окружность с центром в точке О(x0, y0) и радиусом R0, найти точки пересечения линии с осью абсцисс.</div>',
      '<div>Составить программу «сжатия» исходной строки символов: каждая ' +
      'подстрока, состоящая из нескольких вхождений одного и того же символа, ' +
      'должна быть заменена на текст«x(k)», где x- символ, а k- строка, являющаяся ' +
      'записью числа вхождений символа в исходную строку</div>',
  ];

  window.onload = function (){
      document.getElementById("exercice").innerHTML =  ex[0];
      listenerForLi();
  };
  function listenerForLi() {
      var lis = document.getElementById("left").getElementsByTagName("li");
      for (var num = 0; num < lis.length; num++) {
          lis[num].addEventListener("click", function (elem) {
              var el = elem.target;
              document.getElementById("exercice").innerHTML = ex[el.value];
              for (var i = 0; i < lis.length; i++){
                lis[i].classList.remove("active");
              }
              el.classList.add("active");
          });
      }
  }
  function getMonth() {
      month = document.getElementById("solution").getElementsByTagName("input")[0].value;

      return month;
  }
</script>